version: '3.8'

services:
  # Serviço web com Laravel
  web:
    image: tellys/laravel:11-phpfpm84-nginx-redis-supervisor
    container_name: web
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PHP_VERSION: '8.2.4-fpm-bullseye'
    ports:
      - "80:80" # http
      - "443:443" # https
    volumes:
      - ./app:/var/www/app
    networks:
      - app-network
    depends_on:
      - mysql
      - redis
      - mail

  # Serviço MySQL 8.1
  mysql:
    image: mysql:8.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root # Defina uma senha segura
      MYSQL_DATABASE: portal # Nome do banco de dados
      MYSQL_USER: username # Nome do usuário
      MYSQL_PASSWORD: userpass # Senha do usuário
    ports:
      - "3306:3306" # Porta do MySQL
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  # Adminer para gerenciamento do banco de dados
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "9090:8080" # Acesso ao Adminer através da porta 9090
    depends_on:
      - mysql
    networks:
      - app-network

  # Mailpit para testes de e-mail
  mail:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025" # Interface web do Mailpit
      - "1025:1025" # Porta para envio de e-mails
    networks:
      - app-network

  # Redis para cache e fila de jobs
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - .docker/redis/data:/data
    ports:
      - "6379:6379" # Porta do Redis
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
